### ISSUE TITLE
Decode doesn't handle 204 No Content

### ISSUE THREAD

**Issue by truonghnancy** [godaddy/reduxful#14]
I get the following error when using Reduxful to do a PATCH request that returns `204 No Content`.
```
TypeError: Cannot read property 'includes' of null
    at push../node_modules/reduxful/lib/fetchUtils.js.handlers.decode (fetchUtils.js:36)
    at run (es6.promise.js:75)
    at es6.promise.js:92
    at MutationObserver.flush (_microtask.js:18)
```

Looked into the `decode` function in `../src/fetchUtils.js` and I see that we don't do a null check after attempting to pull `content-type` off the headers.

It looks like it's a simple null check fix (and maybe also check the status code). So something like this?

```
...
if (!contentType && response.status === 204) {
    return response;
  } else if (contentType.includes('application/json')) {
...
```

**Comment by kinetifex** [comment]
Fixed in [1.3.1](https://github.com/godaddy/reduxful/releases/tag/v1.3.1)
